"""
Django settings for organic_mind_backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Security settings are driven by environment variables. With DEBUG off the
# process refuses to start unless a real secret key and an explicit host
# allowlist are provided, so a misconfigured deployment fails loudly instead
# of silently running insecure defaults.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Dev-only fallback; never used when DJANGO_DEBUG is False.
        SECRET_KEY = 'django-insecure-5^8kpaxnm2n@j2a+zgm1rtwp!fful)or*q1+d*0(mdtg_jv!&@'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is False.'
        )

# SECURITY WARNING: with DEBUG off there is no wildcard fallback.
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS')
if _allowed_hosts_env:
    ALLOWED_HOSTS = [
        host.strip() for host in _allowed_hosts_env.split(',') if host.strip()
    ]
elif DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    raise ImproperlyConfigured(
        'DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG is False.'
    )

# CORS settings for React frontend. Narrow this to the deployed frontend
# origin(s) in production via DJANGO_CORS_ORIGINS. The WebSocket origin check
# (see asgi.py) reuses this list, so it must cover every origin the SPA is
# served from.
CORS_ALLOW_ALL_ORIGINS = False
_cors_origins_env = os.environ.get('DJANGO_CORS_ORIGINS')
if _cors_origins_env:
    CORS_ALLOWED_ORIGINS = [
        origin.strip() for origin in _cors_origins_env.split(',') if origin.strip()
    ]
elif DEBUG:
    # Dev-only fallback for the local Vite/React dev servers; never used
    # when DJANGO_DEBUG is False.
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
else:
    raise ImproperlyConfigured(
        'DJANGO_CORS_ORIGINS must be set when DJANGO_DEBUG is False.'
    )
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding', 
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# Application definition

INSTALLED_APPS = [
    # Daphne must come first so its ASGI runserver serves WebSockets
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'channels',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Must be near the top
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'organic_mind_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'organic_mind_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# The database is driven by DJANGO_DATABASE_URL so production can point at a
# server database (e.g. postgres://user:pass@host:5432/organic_mind). SQLite
# is only the dev default: it serializes writers at the file level and turns
# select_for_update() into a no-op, so it must not serve production traffic.


def database_config_from_url(url):
    """Translate a database URL into a Django DATABASES entry.

    Supports postgres(ql)://, mysql:// and sqlite:/// URLs. Query-string
    parameters (e.g. ?sslmode=require) are passed through as OPTIONS.
    """
    parsed = urlparse(url)
    engines = {
        'postgres': 'django.db.backends.postgresql',
        'postgresql': 'django.db.backends.postgresql',
        'mysql': 'django.db.backends.mysql',
        'sqlite': 'django.db.backends.sqlite3',
    }
    engine = engines.get(parsed.scheme.lower())
    if engine is None:
        raise ImproperlyConfigured(
            f'Unsupported DJANGO_DATABASE_URL scheme {parsed.scheme!r}; '
            'use postgres, postgresql, mysql or sqlite.'
        )
    if parsed.scheme.lower() == 'sqlite':
        # sqlite:///relative/path, sqlite:////absolute/path or sqlite://:memory:
        name = parsed.netloc + parsed.path
        if name.startswith('/'):
            name = name[1:]
        return {'ENGINE': engine, 'NAME': name}
    options = {key: values[0] for key, values in parse_qs(parsed.query).items()}
    config = {
        'ENGINE': engine,
        'NAME': parsed.path.lstrip('/'),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
    }
    if options:
        config['OPTIONS'] = options
    return config


_database_url = os.environ.get('DJANGO_DATABASE_URL')
if _database_url:
    DATABASES = {'default': database_config_from_url(_database_url)}
elif DEBUG:
    # Dev-only fallback; never used when DJANGO_DEBUG is False.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured(
        'DJANGO_DATABASE_URL must be set when DJANGO_DEBUG is False.'
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# Calendar dates (due_date, event date) are DateFields and are unaffected by
# USE_TZ; the frontend treats them as local YYYY-MM-DD strings. USE_TZ=True
# ensures DateTimeFields (created_at/updated_at) are stored as timezone-aware
# UTC values rather than naive datetimes.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/
# The backend must be chosen explicitly in production: the console backend
# prints verification emails (including the signed activation link) to the
# server log, so it is only acceptable as a dev convenience.
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND')
if not EMAIL_BACKEND:
    if DEBUG:
        # Dev-only fallback: verification emails are printed to the server
        # log. Point DJANGO_EMAIL_BACKEND at an SMTP backend in production.
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    else:
        raise ImproperlyConfigured(
            'DJANGO_EMAIL_BACKEND must be set when DJANGO_DEBUG is False; '
            'the console backend would leak signed verification links to logs.'
        )
DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL',
    'Organic Mind <noreply@organicmind.local>',
)

# Auth hardening knobs
# API tokens older than this many days are rejected (sign in again to get a
# fresh one). WebSocket tickets are single-purpose and expire within seconds.
TOKEN_EXPIRY_DAYS = int(os.environ.get('DJANGO_TOKEN_EXPIRY_DAYS', '30'))
WS_TICKET_MAX_AGE = int(os.environ.get('DJANGO_WS_TICKET_MAX_AGE', '60'))
EMAIL_VERIFICATION_MAX_AGE_SECONDS = int(
    os.environ.get('DJANGO_EMAIL_VERIFICATION_MAX_AGE', str(3 * 24 * 3600))
)


# Logging
# https://docs.djangoproject.com/en/6.1/topics/logging/
# Console-based logging so container orchestrators and process managers can
# capture output. Swap in file/syslog handlers for environments that need them.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Tokens expire after TOKEN_EXPIRY_DAYS instead of living forever.
        'api.authentication.ExpiringTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# Custom user model
AUTH_USER_MODEL = 'api.User'

# Channels configuration for WebSockets
ASGI_APPLICATION = 'organic_mind_backend.asgi.application'

# Channel layers configuration. The in-memory backend only works within a
# single process, so it is a development convenience. For production or
# multi-instance deployments set REDIS_URL (e.g. redis://localhost:6379/0) so
# every process shares a Redis-backed channel layer.
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
