# Generated by Django 6.1 on 2026-08-20 16:33

from django.db import migrations, models


def enable_notification_settings(apps, schema_editor):
    """Default both notification settings to ON for existing users.

    The settings toggles were not wired to any behavior before this change,
    so stored values were inert defaults rather than user choices.
    """
    User = apps.get_model('api', 'User')
    User.objects.update(push_notifications=True, task_reminders=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='task_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            enable_notification_settings,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
