# Generated by Django 6.1 on 2026-08-21 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_task_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='WsTicketNonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nonce', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ws_ticket_nonces',
                'constraints': [models.UniqueConstraint(fields=('nonce',), name='unique_ws_ticket_nonce')],
            },
        ),
    ]
