# Generated by Django 6.1 on 2026-08-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wsticketnonce'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wsticketnonce',
            name='unique_ws_ticket_nonce',
        ),
        migrations.DeleteModel(
            name='WsTicketNonce',
        ),
    ]
